from aiogram.fsm.state import State, StatesGroup

class OrderStates(StatesGroup):
    choosing_cleaning_type = State()
    choosing_room_count = State()
    choosing_bathroom_count = State()
    choosing_additional_services = State()
    entering_address = State()
    confirming_address = State()
    choosing_date = State()
    choosing_time = State()
    waiting_for_photo = State()
    entering_order_name = State()
    entering_order_phone = State()
    confirming_order = State()
    choosing_payment_method = State()
    editing_order = State()
    editing_additional_services = State()
    editing_address = State()
    editing_room_count = State()
    editing_bathroom_count = State()
